<a href="https://colab.research.google.com/github/medistlabo/TCGA_Practice/blob/main/tcga_practice_day19_cox.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install lifelines

Collecting lifelines
  Downloading lifelines-0.30.3-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from lifelines) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from lifelines) (1.16.3)
Requirement already satisfied: pandas<3.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from lifelines) (2.2.2)
Requirement already satisfied: matplotlib>=3.0 in /usr/local/lib/python3.12/dist-packages (from lifelines) (3.10.0)
Requirement already satisfied: autograd>=1.5 in /usr/local/lib/python3.12/dist-packages (from lifelines) (1.8.0)
Collecting autograd-gamma>=0.3 (from lifelines)
  Downloading autograd-gamma-0.5.0.tar.gz (4.0 kB)
  Preparing metadata (setup.py) ... done
Collecting formulaic>=0.2.2 (from lifelines)
  Downloading formulaic-1.2.1-py3-none-any.whl.metadata (7.0 kB)
Collecting interface-meta>=1.2.0 (from formulaic>=0.2.2->lifelines)
  Downloading interface_meta-2.0.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines) (2.21.2)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines) (2.2.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0->lifelines) (1.17.0)
Downloading lifelines-0.30.3-py3-none-any.whl (409 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.1/409.1 kB 7.6 MB/s eta 0:00:00
Downloading formulaic-1.2.1-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 7.4 MB/s eta 0:00:00
Downloading interface_meta-2.0.1-py3-none-any.whl (15 kB)
Building wheels for collected packages: autograd-gamma
  Building wheel for autograd-gamma (setup.py) ... done
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4030 sha256=a7d7ac31911b0a6e375104711d6dddd29fae0aab03e795bc193d89d62485b03a
  Stored in directory: /root/.cache/pip/wheels/50/37/21/0a719b9d89c635e89ff24bd93b862882ad675279552013b2fb
Successfully built autograd-gamma
Installing collected packages: interface-meta, autograd-gamma, formulaic, lifelines
Successfully installed autograd-gamma-0.5.0 formulaic-1.2.1 interface-meta-2.0.1 lifelines-0.30.3

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
from lifelines import CoxPHFitter

In [5]:
data = {
    "patient": ["P1","P2","P3","P4","P5","P6","P7","P8","P9","P10",
                "P11","P12","P13","P14","P15","P16"],

    "expression": [5,12,18,25,30,7,40,22,15,35,28,10,45,8,33,20],

    "survival_month": [50,40,35,20,15,45,10,25,38,12,18,48,8,52,14,28],

    "status": [0,0,1,1,1,0,1,1,0,1,1,0,1,0,1,1]
}

df = pd.DataFrame(data)

df

   patient  expression  survival_month  status
0       P1           5              50       0
1       P2          12              40       0
2       P3          18              35       1
3       P4          25              20       1
4       P5          30              15       1
5       P6           7              45       0
6       P7          40              10       1
7       P8          22              25       1
8       P9          15              38       0
9      P10          35              12       1
10     P11          28              18       1
11     P12          10              48       0
12     P13          45               8       1
13     P14           8              52       0
14     P15          33              14       1
15     P16          20              28       1

In [12]:
cox = CoxPHFitter()
df_cox = df.drop(columns = ["patient"])
df_cox

    expression  survival_month  status
0            5              50       0
1           12              40       0
2           18              35       1
3           25              20       1
4           30              15       1
5            7              45       0
6           40              10       1
7           22              25       1
8           15              38       0
9           35              12       1
10          28              18       1
11          10              48       0
12          45               8       1
13           8              52       0
14          33              14       1
15          20              28       1

In [13]:
cox.fit(
    df_cox,
    duration_col = "survival_month",
    event_col = "status",
)

/usr/local/lib/python3.12/dist-packages/lifelines/fitters/coxph_fitter.py:1614: ConvergenceWarning: Newton-Raphson failed to converge sufficiently. Please see the following tips in the lifelines documentation: https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model
  warnings.warn(

In [14]:
cox.print_summary()

<lifelines.CoxPHFitter: fitted with 16 total observations, 6 right-censored observations>
             duration col = 'survival_month'
                event col = 'status'
      baseline estimation = breslow
   number of observations = 16
number of events observed = 10
   partial log-likelihood = -0.21
         time fit was run = 2026-05-29 00:23:04 UTC

---
            coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
expression  1.56      4.76      0.96           -0.32            3.45                0.72               31.37

            cmp to    z    p  -log2(p)
covariate
expression    0.00 1.62 0.10      3.26
---
Concordance = 1.00
Partial AIC = 2.43
log-likelihood ratio test = 47.76 on 1 df
-log2(p) of ll-ratio test = 37.59